# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kanban < Formula
  desc "Kanban CLI - a cli tool for managin kanban boards"
  homepage "https://github.com/alcb1310/kanban"
  version "0.0.2"
  license "MIT"

  on_macos do
    url "https://github.com/alcb1310/kanban/releases/download/v0.0.2/kanban_0.0.2_darwin_all.tar.gz"
    sha256 "65434ee222d9183e1ddd813a6291e0b5fa3dbfd71f0f1c26fe4ae21235e22389"

    def install
      bin.install "kanban"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcb1310/kanban/releases/download/v0.0.2/kanban_0.0.2_linux_arm64.tar.gz"
      sha256 "a06a08e388d18f8b30442ea4d675466e1ec7ebb1e48987ac505a5c2c402c9b6e"

      def install
        bin.install "kanban"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alcb1310/kanban/releases/download/v0.0.2/kanban_0.0.2_linux_amd64.tar.gz"
      sha256 "a8bb009fac45219b0514c7ffc4a61f0f03c1618466c2c26c791a2718faa8cfe0"

      def install
        bin.install "kanban"
      end
    end
  end
end
