# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kanban < Formula
  desc "Kanban CLI - a cli tool for managin kanban boards"
  homepage "https://github.com/alcb1310/kanban"
  version "0.0.12"
  license "MIT"
  depends_on :macos

  url "https://github.com/alcb1310/kanban/releases/download/v0.0.12/kanban_0.0.12_darwin_all.tar.gz"
  sha256 "e66ef31e87712939c70cb4a1aa83278288c2088ec4ab04607936bad01a2499e8"

  def install
    bin.install "kanban"
  end
end
